DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    studio TEXT,
    cast TEXT,
    director TEXT,
    genre TEXT NOT NULL,
    year INTEGER NOT NULL,
    rating REAL NOT NULL,
    description TEXT,
    poster_url TEXT
);

INSERT INTO movies (id, title, studio, cast, director, genre, year, rating, description, poster_url) VALUES
(1, 'Inception', 'Warner Bros.',
 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy, Ken Watanabe',
 'Christopher Nolan',
 'Sci-fi / Thriller', 2010, 8.8,
 'Dom Cobb, mistrz kradzieży sekretów z umysłów poprzez sny, otrzymuje zadanie zaszczepienia idei w umyśle biznesmena. Aby to zrobić, jego zespół konstruuje wielowarstwowy sen, gdzie granica między fikcją a jawą zaczyna się zacierać.',
 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg'),

(2, 'The Dark Knight', 'Warner Bros.',
 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman',
 'Christopher Nolan',
 'Akcja / Kryminał', 2008, 9.0,
 'Batman, Gordon i Harvey Dent próbują oczyścić Gotham z przestępczości. Na ich drodze staje Joker — anarchista pragnący udowodnić, że każdy może zostać złamany.',
 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'),

(3, 'Interstellar', 'Paramount / Warner Bros.',
 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine, Matt Damon',
 'Christopher Nolan',
 'Sci-fi / Dramat', 2014, 8.6,
 'Umierająca Ziemia zmusza ludzi do poszukiwania nowego domu w kosmosie. Cooper dołącza do misji przez tunel czasoprzestrzenny, gdzie czas i rodzina nabierają innego znaczenia.',
 'https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg'),

(4, 'Avatar', '20th Century Fox',
 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez',
 'James Cameron',
 'Sci-fi / Przygodowy', 2009, 7.9,
 'Sparaliżowany żołnierz Jake trafia na Pandorę jako awatar, gdzie odkrywa piękno lokalnej kultury i konflikt z ludźmi niszczącymi planetę.',
 'https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg'),

(5, 'Titanic', 'Paramount / 20th Century Fox',
 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Bill Paxton',
 'James Cameron',
 'Romans / Dramat', 1997, 7.9,
 'Młoda arystokratka Rose i ubogi artysta Jack zakochują się podczas dziewiczego rejsu Titanica, co prowadzi do wielkiej tragedii.',
 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg'),

(6, 'Matrix', 'Warner Bros.',
 'Keanu Reeves, Carrie-Anne Moss, Laurence Fishburne, Hugo Weaving, Joe Pantoliano',
 'Lana Wachowski, Lilly Wachowski',
 'Sci-fi / Akcja', 1999, 8.7,
 'Neo odkrywa, że rzeczywistość jest symulacją stworzoną przez maszyny, a on sam może być tym, który zakończy ich kontrolę.',
 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg'),

(7, 'Gladiator', 'DreamWorks / Universal',
 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Richard Harris, Djimon Hounsou',
 'Ridley Scott',
 'Dramat historyczny / Akcja', 2000, 8.5,
 'Zdradzony generał Maximus zostaje zmuszony do życia jako gladiator i wyrusza w symboliczną drogę zemsty na tyranie Kommodusie.',
 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg'),

(8, 'Forrest Gump', 'Paramount',
 'Tom Hanks, Robin Wright, Gary Sinise, Sally Field, Mykelti Williamson',
 'Robert Zemeckis',
 'Dramat / Komediodramat', 1994, 8.8,
 'Forrest — człowiek o szczerym sercu — przypadkowo uczestniczy w najważniejszych wydarzeniach XX wieku, dążąc do miłości Jenny.',
 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg'),

(9, 'Pulp Fiction', 'Miramax',
 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis, Ving Rhames',
 'Quentin Tarantino',
 'Kryminał / Dramat', 1994, 8.9,
 'Splecione historie gangsterów i wyrzutków tworzą niepowtarzalny styl opowieści pełnej groteski, brutalności i kultowych dialogów.',
 'https://m.media-amazon.com/images/I/71c05lTE03L._AC_UF894,1000_QL80_.jpg'),

(10, 'Star Wars: A New Hope', 'Lucasfilm',
 'Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guinness, Peter Cushing',
 'George Lucas',
 'Sci-fi / Przygodowy', 1977, 8.6,
 'Młody Luke Skywalker staje do walki z Imperium, odkrywając swój potencjał jako rycerz Jedi.',
 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg'),

(11, 'Jurassic Park', 'Universal',
 'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough, Samuel L. Jackson',
 'Steven Spielberg',
 'Sci-fi / Przygodowy', 1993, 8.1,
 'Eksperyment klonowania dinozaurów wymyka się spod kontroli, zmieniając park rozrywki w arenę walki o przetrwanie.',
 'https://image.tmdb.org/t/p/w500/9i3plLl89DHMz7mahksDaAo7HIS.jpg'),

(12, 'The Lord of the Rings: Fellowship of the Ring', 'New Line Cinema',
 'Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom, Sean Astin',
 'Peter Jackson',
 'Fantasy / Przygodowy', 2001, 8.8,
 'Frodo i Drużyna Pierścienia wyruszają w niebezpieczną misję zniszczenia artefaktu zdolnego zniszczyć świat.',
 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'),

(13, 'The Avengers', 'Marvel Studios',
 'Robert Downey Jr., Chris Evans, Chris Hemsworth, Scarlett Johansson, Mark Ruffalo',
 'Joss Whedon',
 'Akcja / Sci-fi', 2012, 8.0,
 'Avengersi jednoczą siły, by powstrzymać Lokiego i inwazję obcych na Ziemię.',
 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg'),

(14, 'The Lion King', 'Disney',
 'Matthew Broderick, Jeremy Irons, James Earl Jones, Moira Kelly, Rowan Atkinson',
 'Roger Allers, Rob Minkoff',
 'Animacja / Dramat', 1994, 8.5,
 'Simba musi odnaleźć swoje miejsce w świecie i stawić czoła zdradzie wuja Skazy.',
 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg'),

(15, 'Harry Potter and the Sorcerer''s Stone', 'Warner Bros.',
 'Daniel Radcliffe, Emma Watson, Rupert Grint, Alan Rickman, Maggie Smith',
 'Chris Columbus',
 'Fantasy / Przygodowy', 2001, 7.6,
 'Jedenastoletni Harry odkrywa, że jest czarodziejem, i rozpoczyna naukę w Hogwarcie, gdzie czeka go pierwsza wielka przygoda.',
 'https://image.tmdb.org/t/p/w500/hziiv14OpD73u9gAak4XDDfBKa2.jpg');